assets/css/global.css, index.html
Added counter section and a global.css file for its working.
Please review the pull request.
=> Added Counter section

assets/css/main.css
=> x-axis scrolling fixed

assets/css/main.css
Reverts codeuino/website-www.codeuino.org#37
=> Revert "Update main.css"

assets/css/main.css
Added margin. Also works well in Mobile (mobile-friendly)
=> Added Margin

index.html
Fixes #44 
After merging this PR the donate popup will appear on clicking the donate-us button.
Also, I have reformated index.html as its code was not properly formatted.
=> popup binded to donate-us button

css/style.css, index.html
In this commit I have added new footer to the website.
Have a look at the changes in the below gif.
=> new footer added

css/style.css, index.html
=> Solved Button width is not set properly #55

css/donation-popup.css
I have just updated the .popup-style padding-top.
=> Updated padding for .popup-style

css/style.css
Reverts codeuino/website-www.codeuino.org#67
The changes had no effect
=> Revert "Submit query button padding issue solved"

css/style.css, index.html
1.Corrected typos.
2.Made some part of footer of main page responsive for mobile devices. I am enclosing screenshots
=>  Removed links from footer for mobile view

Projects.html, about.html, contact.html, css/donation-popup.css
Now it is working in all pages.
=> Donate us popup fixed

css/donation-popup.css
The padding for the donate us popup is fixed.
=> Fixed padding in donate us popup #98

views/team.html
=> removed Hrishi as requested

package-lock.json, package.json, views/index.html
Made spellings and grammatical corrections, Removed lorem ipsum div under what we do
Made superior grammar corrections to the website text content, also there was an unnecessary div under the heading of WHAT WE DO which had gibberish written under it using lorem ipsum, hence was unnecessary therefore was removed.
=> Made spellings and grammatical corrections, Removed lorem ipsum div

views/index.html
Provided aesthetic spacing under latest activities.
Kindly review.
=> Provided spacing between the divs under recent activity.

README.md
Prettified `README.md` with the following badges: 
[![License: GPL v3](https://img.shields.io/badge/License-GPLv3-blue.svg?logo=github)](https://www.gnu.org/licenses/gpl-3.0) [![GitHub forks](https://img.shields.io/github/forks/codeuino/website-www.codeuino.org?logo=github)](https://github.com/codeuino/website-www.codeuino.org/network) [![GitHub stars](https://img.shields.io/github/stars/codeuino/website-www.codeuino.org?logo=github)](https://github.com/codeuino/website-www.codeuino.org/stargazers)
[![GitHub issues](https://img.shields.io/github/issues/codeuino/website-www.codeuino.org?logo=github)](https://github.com/codeuino/website-www.codeuino.org/issues) ![GitHub closed issues](https://img.shields.io/github/issues-closed/codeuino/website-www.codeuino.org?logo=github)
[![PRs …
=> Added GitHub badges

public/index.html, public/manifest.json, src/App.css, src/App.js, src/pages/Team/Team.js
**Removed padding from navbar**
**Removed overflow from navbar**
**Updated title of the page**
=> improved navbar padding, view, title of page

src/App.js, src/components/Footer/Footer.css, src/components/Footer/index.js, src/components/NavBar/NavBar.css, src/components/NavBar/index.js, src/pages/About/About.css, src/pages/About/About.js, src/pages/Team/Team.js
The purpose of refactoring is to keep codebase modular and clean.
The updated UI has the following changes:
- The navbar has a box-shadow.
- The footer color is changed and added padding.
- In about page, the text is justified and added media queries to cover logo on it.
**Screenshots**
@jaskirat2000 Please review and let me know changes.
=> Added separate component for navbar and footer and updated UI

src/components/NavBar/index.js
Previously the link was directed to the blog list page.
=> Fixed the Join Us link

src/components/ScrollToTopBtn/ScrollToTopBtn.css, src/components/ScrollToTopBtn/ScrollToTopBtn.js, src/pages/About/About.js, src/pages/Home/NewHome.js, src/pages/Team/Team.js
I have updated the website with a scroll to top button.
=> Added a scroll to top component

.dockerignore, Dockerfile-dev, README.md, package.json
Running code on different machine is tough, so in this Pull request, I'm adding a docker file for development with instructions in README.md.
=> Added dockerfile for development

src/pages/Team/BoardMembers.js
changed the GitHub repo link to jaskiratsingh2000
=> corrected repo link
